-- Algolassi 4.0: one report per authenticated user per message.
create table if not exists public.chat_message_reports (
    id bigint generated by default as identity primary key,
    message_id bigint not null references public.chat_messages(id) on delete cascade,
    reporter_id uuid not null references auth.users(id) on delete cascade,
    created_at timestamptz not null default now(),
    constraint chat_message_reports_unique unique (message_id, reporter_id)
);

create index if not exists chat_message_reports_message_id_idx
    on public.chat_message_reports(message_id);

alter table public.chat_message_reports enable row level security;

drop policy if exists "Reports are privately readable by reporter" on public.chat_message_reports;
create policy "Reports are privately readable by reporter"
on public.chat_message_reports for select
using (auth.uid() = reporter_id);

revoke all on public.chat_message_reports from public;
revoke all on public.chat_message_reports from anon;
revoke all on public.chat_message_reports from authenticated;

drop function if exists public.report_chat_message(bigint);
create or replace function public.report_chat_message(p_message_id bigint)
returns table (reported boolean, author_reputation integer)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_reporter uuid := auth.uid();
    v_author uuid;
    v_rep integer;
    v_reported boolean := false;
begin
    if v_reporter is null then
        raise exception 'Authentication required';
    end if;

    select user_id into v_author
    from public.chat_messages
    where id = p_message_id;

    if not found then
        raise exception 'Chat message not found';
    end if;

    if v_author is null then
        raise exception 'Guest messages cannot currently be reported';
    end if;

    if v_author = v_reporter then
        raise exception 'You cannot report your own message';
    end if;

    if exists (
        select 1 from public.chat_message_reports
        where message_id = p_message_id and reporter_id = v_reporter
    ) then
        select reputation into v_rep from public.profiles where user_id = v_author;
        return query select false, coalesce(v_rep, 0);
    end if;

    insert into public.chat_message_reports(message_id, reporter_id)
    values (p_message_id, v_reporter);

    update public.profiles
    set reputation = greatest(0, reputation - 1), updated_at = now()
    where user_id = v_author
    returning reputation into v_rep;

    v_reported := true;
    return query select v_reported, coalesce(v_rep, 0);
end;
$$;

revoke all on function public.report_chat_message(bigint) from public;
grant execute on function public.report_chat_message(bigint) to authenticated;
