-- Algolassi community chat Phase 2.
-- Guests may post with a browser-generated guest_id; authenticated users
-- must submit their own Supabase auth user_id. Messages are public/read-only.

CREATE TABLE IF NOT EXISTS public.chat_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  guest_id text,
  username text NOT NULL,
  message text NOT NULL CHECK (char_length(trim(message)) BETWEEN 1 AND 500),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chat_messages_identity_check CHECK (
    (user_id IS NOT NULL AND guest_id IS NULL)
    OR
    (user_id IS NULL AND guest_id IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS chat_messages_created_at_idx
  ON public.chat_messages(created_at DESC);

ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT ON public.chat_messages TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.chat_messages_id_seq TO anon, authenticated;

DROP POLICY IF EXISTS "Anyone can read chat messages" ON public.chat_messages;
CREATE POLICY "Anyone can read chat messages"
ON public.chat_messages
FOR SELECT
TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "Guests can send chat messages" ON public.chat_messages;
CREATE POLICY "Guests can send chat messages"
ON public.chat_messages
FOR INSERT
TO anon
WITH CHECK (
  user_id IS NULL
  AND guest_id IS NOT NULL
);

DROP POLICY IF EXISTS "Authenticated users can send chat messages" ON public.chat_messages;
CREATE POLICY "Authenticated users can send chat messages"
ON public.chat_messages
FOR INSERT
TO authenticated
WITH CHECK (
  user_id = (SELECT auth.uid())
  AND guest_id IS NULL
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'chat_messages'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.chat_messages;
  END IF;
END;
$$;
