-- Algolassi Phase 3C: reputation reactions
-- Run this migration in Supabase SQL Editor.

create table if not exists public.chat_message_reactions (
    id bigint generated by default as identity primary key,
    message_id bigint not null references public.chat_messages(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    reaction text not null default 'positive',
    created_at timestamptz not null default now(),
    constraint chat_message_reactions_type check (reaction = 'positive'),
    constraint chat_message_reactions_unique unique (message_id, user_id, reaction)
);

create index if not exists chat_message_reactions_message_id_idx
    on public.chat_message_reactions(message_id);

create index if not exists chat_message_reactions_user_id_idx
    on public.chat_message_reactions(user_id);

alter table public.chat_message_reactions enable row level security;

drop policy if exists "Reactions are publicly readable"
    on public.chat_message_reactions;
create policy "Reactions are publicly readable"
on public.chat_message_reactions
for select
using (true);

drop policy if exists "Users can add their own reactions"
    on public.chat_message_reactions;
create policy "Users can add their own reactions"
on public.chat_message_reactions
for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can remove their own reactions"
    on public.chat_message_reactions;
create policy "Users can remove their own reactions"
on public.chat_message_reactions
for delete
using (auth.uid() = user_id);

-- Securely toggle a positive reaction and update the message author's reputation.
-- The function runs with definer privileges so clients cannot directly modify reputation.
create or replace function public.toggle_chat_positive_reaction(p_message_id bigint)
returns table (reacted boolean, reaction_count bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_user_id uuid := auth.uid();
    v_author_id uuid;
    v_reacted boolean;
    v_count bigint;
begin
    if v_user_id is null then
        raise exception 'Authentication required';
    end if;

    select user_id into v_author_id
    from public.chat_messages
    where id = p_message_id;

    if not found then
        raise exception 'Chat message not found';
    end if;

    if exists (
        select 1 from public.chat_message_reactions
        where message_id = p_message_id
          and user_id = v_user_id
          and reaction = 'positive'
    ) then
        delete from public.chat_message_reactions
        where message_id = p_message_id
          and user_id = v_user_id
          and reaction = 'positive';
        v_reacted := false;

        if v_author_id is not null then
            update public.profiles
            set reputation = greatest(0, reputation - 1), updated_at = now()
            where user_id = v_author_id;
        end if;
    else
        insert into public.chat_message_reactions(message_id, user_id, reaction)
        values (p_message_id, v_user_id, 'positive');
        v_reacted := true;

        if v_author_id is not null and v_author_id <> v_user_id then
            update public.profiles
            set reputation = reputation + 1, updated_at = now()
            where user_id = v_author_id;
        end if;
    end if;

    select count(*) into v_count
    from public.chat_message_reactions
    where message_id = p_message_id
      and reaction = 'positive';

    return query select v_reacted, v_count;
end;
$$;

revoke all on function public.toggle_chat_positive_reaction(bigint) from public;
grant execute on function public.toggle_chat_positive_reaction(bigint) to authenticated;
