-- Algolassi 11.0: one-time tutorial quiz reputation rewards
-- Run this migration in the Supabase SQL Editor.

create table if not exists public.tutorial_quiz_rewards (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    quiz_key text not null,
    points integer not null default 1,
    created_at timestamptz not null default now(),
    constraint tutorial_quiz_rewards_points_check check (points > 0),
    constraint tutorial_quiz_rewards_unique unique (user_id, quiz_key)
);

create index if not exists tutorial_quiz_rewards_user_id_idx
    on public.tutorial_quiz_rewards(user_id);

alter table public.tutorial_quiz_rewards enable row level security;

drop policy if exists "Users can read their own quiz rewards"
    on public.tutorial_quiz_rewards;
create policy "Users can read their own quiz rewards"
on public.tutorial_quiz_rewards
for select
using (auth.uid() = user_id);

create or replace function public.award_tutorial_quiz_reputation(
    p_quiz_key text,
    p_points integer default 1
)
returns table (awarded boolean, reputation integer)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_user_id uuid := auth.uid();
    v_awarded boolean := false;
    v_reputation integer := 0;
begin
    if v_user_id is null then
        raise exception 'Authentication required';
    end if;

    if coalesce(length(trim(p_quiz_key)), 0) = 0 then
        raise exception 'Quiz key is required';
    end if;

    if coalesce(p_points, 0) <= 0 or p_points > 10 then
        raise exception 'Invalid quiz points';
    end if;

    insert into public.tutorial_quiz_rewards(user_id, quiz_key, points)
    values (v_user_id, trim(p_quiz_key), p_points)
    on conflict (user_id, quiz_key) do nothing;

    if found then
        update public.profiles
        set reputation = reputation + p_points,
            updated_at = now()
        where user_id = v_user_id
        returning reputation into v_reputation;
        v_awarded := true;
    else
        select reputation into v_reputation
        from public.profiles
        where user_id = v_user_id;
    end if;

    return query select v_awarded, coalesce(v_reputation, 0);
end;
$$;

revoke all on function public.award_tutorial_quiz_reputation(text, integer) from public;
grant execute on function public.award_tutorial_quiz_reputation(text, integer) to authenticated;
